<?php

/**
 * BaseBill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date
 * @property string $place
 * @property float $totalPrice
 * @property integer $carId
 * @property integer $userId
 * @property string $type
 * @property integer $fuelTypeId
 * @property float $liters
 * @property float $priceForLiter
 * @property float $distanceTillLastBill
 * @property clob $description
 * 
 * @method timestamp getDate()                 Returns the current record's "date" value
 * @method string    getPlace()                Returns the current record's "place" value
 * @method float     getTotalPrice()           Returns the current record's "totalPrice" value
 * @method integer   getCarId()                Returns the current record's "carId" value
 * @method integer   getUserId()               Returns the current record's "userId" value
 * @method string    getType()                 Returns the current record's "type" value
 * @method integer   getFuelTypeId()           Returns the current record's "fuelTypeId" value
 * @method float     getLiters()               Returns the current record's "liters" value
 * @method float     getPriceForLiter()        Returns the current record's "priceForLiter" value
 * @method float     getDistanceTillLastBill() Returns the current record's "distanceTillLastBill" value
 * @method clob      getDescription()          Returns the current record's "description" value
 * @method Bill      setDate()                 Sets the current record's "date" value
 * @method Bill      setPlace()                Sets the current record's "place" value
 * @method Bill      setTotalPrice()           Sets the current record's "totalPrice" value
 * @method Bill      setCarId()                Sets the current record's "carId" value
 * @method Bill      setUserId()               Sets the current record's "userId" value
 * @method Bill      setType()                 Sets the current record's "type" value
 * @method Bill      setFuelTypeId()           Sets the current record's "fuelTypeId" value
 * @method Bill      setLiters()               Sets the current record's "liters" value
 * @method Bill      setPriceForLiter()        Sets the current record's "priceForLiter" value
 * @method Bill      setDistanceTillLastBill() Sets the current record's "distanceTillLastBill" value
 * @method Bill      setDescription()          Sets the current record's "description" value
 * 
 * @package    CarCalc
 * @subpackage model
 * @author     Wojciech Sznapka
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bill');
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('place', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('totalPrice', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('carId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('userId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fuelTypeId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('liters', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('priceForLiter', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('distanceTillLastBill', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->setSubClasses(array(
             'FuelBill' => 
             array(
              'type' => 'F',
             ),
             'ShopBill' => 
             array(
              'type' => 'S',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}