<?php

/**
 * BaseCar2User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $car_id
 * @property integer $user_id
 * 
 * @method integer  getCarId()   Returns the current record's "car_id" value
 * @method integer  getUserId()  Returns the current record's "user_id" value
 * @method Car2User setCarId()   Sets the current record's "car_id" value
 * @method Car2User setUserId()  Sets the current record's "user_id" value
 * 
 * @package    CarCalc
 * @subpackage model
 * @author     Wojciech Sznapka
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCar2User extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car2_user');
        $this->hasColumn('car_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}