<?php

/**
 * BaseFuelBill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property FuelType $FuelType
 * @property Car $Car
 * @property User $User
 * 
 * @method FuelType getFuelType() Returns the current record's "FuelType" value
 * @method Car      getCar()      Returns the current record's "Car" value
 * @method User     getUser()     Returns the current record's "User" value
 * @method FuelBill setFuelType() Sets the current record's "FuelType" value
 * @method FuelBill setCar()      Sets the current record's "Car" value
 * @method FuelBill setUser()     Sets the current record's "User" value
 * 
 * @package    CarCalc
 * @subpackage model
 * @author     Wojciech Sznapka
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuelBill extends Bill
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FuelType', array(
             'local' => 'fuelTypeId',
             'foreign' => 'id'));

        $this->hasOne('Car', array(
             'local' => 'carId',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'userId',
             'foreign' => 'id'));
    }
}