<?php

/**
 * BaseFuelType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property float $fuelTankRate
 * @property Doctrine_Collection $FuelBill
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method float               getFuelTankRate() Returns the current record's "fuelTankRate" value
 * @method Doctrine_Collection getFuelBill()     Returns the current record's "FuelBill" collection
 * @method FuelType            setName()         Sets the current record's "name" value
 * @method FuelType            setFuelTankRate() Sets the current record's "fuelTankRate" value
 * @method FuelType            setFuelBill()     Sets the current record's "FuelBill" collection
 * 
 * @package    CarCalc
 * @subpackage model
 * @author     Wojciech Sznapka
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuelType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fuel_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fuelTankRate', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FuelBill', array(
             'local' => 'id',
             'foreign' => 'fuelTypeId'));
    }
}