<?php

/**
 * BaseCar2User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $carId
 * @property integer $userId
 * 
 * @method integer  getCarId()  Returns the current record's "carId" value
 * @method integer  getUserId() Returns the current record's "userId" value
 * @method Car2User setCarId()  Sets the current record's "carId" value
 * @method Car2User setUserId() Sets the current record's "userId" value
 * 
 * @package    CarCalc
 * @subpackage model
 * @author     Wojciech Sznapka
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCar2User extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car2_user');
        $this->hasColumn('carId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('userId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}