<?php

/**
 * Car2UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Car2UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Car2UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Car2User');
    }
}