<?php

/**
 * CarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Car');
    }

    /**
     * Finds all cars and returns them as an objects
     *  
     * @author Wojciech Sznapka <wojciech.sznapka@xsolve.pl> 
     * @access public
     * 
     * @return Car[]
     */
    public function findAllCars()
    {
      $dql = Doctrine_Query::create()
        ->from("Car c")
        ->leftJoin("c.Users");
      return $dql->execute();
    }

    /**
     * Finds all cars assigned to user given by user id
     *  
     * @author Wojciech Sznapka <wojciech.sznapka@xsolve.pl> 
     * @access public
     * 
     * @param  int $userId 
     * @return Car[]
     */
    public function findAllCarsAssignedToUser($userId)
    {
      if ((int)$userId == 0) {
        throw new InvalidArgumentException("userId should be int");
      }
      $dql = Doctrine_Query::create()
        ->from("Car c")
        ->leftJoin("c.Users u")
        ->where("u.id = ?", $userId);
      return $dql->execute();
    }
}
