<?php

/**
 * CarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Car');
    }

    /**
     * Finds all cars and returns them as an objects
     *  
     * @author Wojciech Sznapka <wojciech.sznapka@xsolve.pl> 
     * @access public
     * 
     * @return Car[]
     */
    public function findAllCars()
    {
      $dql = Doctrine_Query::create()
        ->From("Car c");
      return $dql->execute();
    }
}
