<?php

/**
 * FuelBillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuelBillTable extends BillTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuelBillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FuelBill');
    }
}