<?php

/**
 * FuelTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuelTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuelTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FuelType');
    }
}