<?php

/**
 * ShopBillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopBillTable extends BillTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopBillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopBill');
    }
}