<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }

    /**
     * Finds all users 
     *  
     * @author Wojciech Sznapka <wojciech.sznapka@xsolve.pl> 
     * @access public
     * 
     * @return User[]
     */
    public function findAllUsers()
    {
      $dql = Doctrine_Query::create()
        ->from("User u")
        ->leftJoin("u.Cars");
      return $dql->execute();
    }
}
