# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=CarCalc
      username: root
      password: 

dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'sqlite:%SF_DATA_DIR%/CarCalc.db'

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'sqlite::memory:'
