User:
  columns:
    id:         {type: integer, primary: true, autoincrement: true}
    username:   {type: string(255), notnull: true}
    password:   {type: string(255), notnull: true}
    lastLogin:  {type: timestamp}
  actAs: 
    Timestampable: ~
  
Car:
  columns:
    id:         {type: integer, primary: true, autoincrement: true}
    name:       {type: string(255), notnull: true}
    model:      {type: string(255), notnull: true}
    brand:      {type: string(255), notnull: true}
    year:       {type: int}
  actAs: 
    Timestampable: ~
  relations:
    Users:
      class:        User
      foreignAlias: Cars
      refClass:     Car2User
      local:        userId
      foreign:      carId

Car2User: 
  columns:
    carId:     {type: integer, notnull: true}
    userId:    {type: integer, notnull: true}

FuelType:
  columns:
    name:         {type: string(255), notnull: true}
    fuelTankRate: {type: float}

Bill:
  columns:
    date:       {type: timestamp, notnull: true}
    place:      {type: string(255), notnull: true}
    totalPrice: {type: float}
    carId:      {type: integer, notnull: true}
    userId:     {type: integer, notnull: true}
  actAs:
    Timestampable: ~


FuelBill:
  inheritance:
    extends:    Bill
    type:       column_aggregation
    keyField:   type
    keyValue:   'F'
  columns:
    fuelTypeId:           {type: integer}
    liters:               {type: float}
    priceForLiter:        {type: float}
    distanceTillLastBill: {type: float}
  relations:
    FuelType:
      class: FuelType
      local: fuelTypeId
    Car:
      class: Car
      local: carId
      foreignAlias: FuelBills
    User:
      class: User
      local: userId
      foreignAlias: FuelBills
    
ShopBill:
  inheritance:
    extends:    Bill
    type:       column_aggregation
    keyField:   type
    keyValue:   'S'
  columns:
    description: {type: clob}
  relations:
    Car:
      class: Car
      local: carId
      foreignAlias: FuelBills
    User:
      class: User
      local: userId
      foreignAlias: FuelBills
